### ISSUE TITLE
Modbus Map?

### ISSUE THREAD

**Issue by stebbo63** [thomasfa18/solar-sungrow#1]
Hi thomasfa18,

I'm wanting to write my own application in C#.  I note that you mentioned that you had the official modbus map and was wanting to know if I could get a copy?  In particular, I'm after values up around the 13,000's to be able to monitor my hybrid inverter.

I've seen Meltaxa's list over at SolarIoT, but was hoping to try to get a more inclusive list of the registers up around where the battery details are stored.

Thanks,
Chris.

**Comment by thomasfa18** [comment]
Hi Chris,

I'd love to help you out but sungrow push a firmware update about 3 months ago which either shifted all of the registers, or encrypted them (might just be xor with the serial number But I was never able to test).
Also, they changed the comms protocol over WiFi removing the ability to directly connect and poll the registers over modbustcp.
I have another package that scrapes their web services but as far as an offline poller this project is dead.
You may be able to try a mitm or dns hijack to your own local service but for me it wasn't worth the time investment.

**Comment by stebbo63** [comment]
Hi Thomasfa18,
thanks for the reply.  I actually managed to get a hold of the modbus map and am currently writing my app in c# which is coming along nicely (albeit slowly).
Cheers,
Chris.

**Comment by thomasfa18** [comment]
Nice. What version is the map you got?
Can you still initiate connection to your model inverter?

**Comment by stebbo63** [comment]
Hi thomasfa18,
I have version 1.0.19 dated 28/05/19.  Yes, I can still contact my inverter using modbustcp.
Are you able to view my email address and send me an email directly?  happy to discuss my project via email.
Cheers,
Chris.

**Comment by thomasfa18** [comment]
Sent a pm on whirlpool

**Comment by rpvelloso** [comment]
Hi,

I have an SG4K, where can I get the modbus map? Thanks!

**Comment by Hantuch** [comment]
Hello, @thomasfa18 , is the registers map in this repo still valid? or have they changed it? got any clue how to get one??
